# Autogenerated wrapper script for CGNS_jll for x86_64-linux-gnu
export libcgns

using PackageSpec(
  name = HDF5_jll
  uuid = 0234f1f7-429e-5d53-9886-15a909be8d59
  version = *
)
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `libcgns`
const libcgns_splitpath = ["lib", "libcgns.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libcgns_path = ""

# libcgns-specific global declaration
# This will be filled out by __init__()
libcgns_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libcgns = "libcgns.so.3.4"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"CGNS")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # We first need to add to LIBPATH_list the libraries provided by Julia
    append!(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)])
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (PackageSpec(
  name = HDF5_jll
  uuid = 0234f1f7-429e-5d53-9886-15a909be8d59
  version = *
).PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (PackageSpec(
  name = HDF5_jll
  uuid = 0234f1f7-429e-5d53-9886-15a909be8d59
  version = *
).LIBPATH_list,))

    global libcgns_path = normpath(joinpath(artifact_dir, libcgns_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libcgns_handle = dlopen(libcgns_path)
    push!(LIBPATH_list, dirname(libcgns_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

